### ISSUE TITLE
Enhancements for Activity Timer Screen

### ISSUE THREAD

**Issue by nur-hidayati** [nur-hidayati/focusnest#32]
**Tasks:**

1. **Default Label Setting:**
- [x] For first-time users and users without any existing timer records, set the initial label to "Work".
- [x] If a user has set a custom label, always display the user-defined label.

**2. Default Timer Setting:**
- [x] For first-time users and users without any existing timer records, set the initial timer to "15 mins".
- [x] If a user has set a custom timer duration, always display the user-defined timer.

**3. Recent Timer Activities:**
- [x] Display the last 10 records of timer activities in the "Recents" section.
- [x] User can slide to delete Recent Timer
- [x] Delete will only remove it from Shared Preference, not the database

**Notes**
- Ensure that the initial settings for the label and timer are applied only when there are no previous records or settings.
- Persist user-defined labels and timers across sessions.
- Ensure the "Recents" section is dynamically updated as new timer activities are recorded.
